# Generated by Django 4.1.7 on 2023-03-02 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pedido', models.IntegerField(verbose_name='Numero do pedido')),
                ('status', models.CharField(max_length=20, verbose_name='Estatus do pedido')),
                ('operation', models.CharField(max_length=30, verbose_name='Operação')),
                ('location', models.CharField(max_length=35, verbose_name='Localização')),
                ('distacia', models.CharField(max_length=5, verbose_name='Distancia')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
            ],
        ),
    ]
